server:
  port: 6789

netty:
  host: 127.0.0.1
  port: 8889
  route: webSocket      # webSocket建立连接的路由
  bossThreadCount: 200
  workThreadCount: 200
  maxFramePayloadLength: 1048576   #最大数据帧的长度,与前端文件分块大小保持一致    -- 1M -- 1024*1024*5


spring:
  # mysql配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/chat_room?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 0
    pool:
      max-active: 100     # 最大活跃连接数
      max-idle: 10        # 最大空闲连接数
      max-wait: 100000    # 创建链接的超时时间
      min-idle: 2         # 最小空闲连接数

    # templates 模板引擎配置
  thymeleaf:
     mode: LEGACYHTML5  # 不进未关闭标签检查，需配合nekohtml使用
     encoding: UTF-8
     cache: false     # 关闭缓存
     prefix: classpath:/templates/
     suffix: .html



# mybatis 配置
mybatis:
    mapperLocations: classpath:mapper/*.xml   # 配置mybatis的xml扫描路径